# Generated by Django 5.1.6 on 2026-04-22 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_order_escrow_status_orderreview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="logistics_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[("LOCAL", "Locale"), ("INTERNATIONAL", "Internationale")],
                default="LOCAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="platform_commission_rate",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="order",
            name="escrow_status",
            field=models.CharField(
                choices=[
                    ("HELD", "Bloque chez PayDunya"),
                    ("SPLIT_LOCKED", "Split escrow bloque"),
                    ("PARTIALLY_RELEASED", "Partiellement libere"),
                    ("FROZEN", "Gele"),
                    ("REFUNDED", "Rembourse"),
                    ("RELEASED", "Debloque au vendeur"),
                ],
                default="HELD",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("SOURCING", "Sourcing fournisseur"),
                    ("SUPPLIER_VERIFIED", "Fournisseur verifie"),
                    ("ADMIN_APPROVED", "Validation admin"),
                    ("SHIPPING", "En expédition"),
                    ("DISPUTED", "En litige"),
                    ("REFUNDED", "Remboursee"),
                    ("CONFIRMED", "Confirmee"),
                    ("DELIVERED", "Livree"),
                    ("COMPLETED", "Finalisee"),
                    ("CANCELLED", "Annulee"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="OrderEscrow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "escrow_type",
                    models.CharField(
                        choices=[
                            ("LOCAL", "Escrow local"),
                            ("SUPPLIER", "Escrow fournisseur"),
                            ("LOGISTICS", "Escrow logistique"),
                        ],
                        max_length=16,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "released_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("LOCKED", "Bloque"),
                            ("READY", "Pret a etre libere"),
                            ("RELEASED", "Libere"),
                            ("FROZEN", "Gele"),
                            ("REFUNDED", "Rembourse"),
                        ],
                        default="LOCKED",
                        max_length=12,
                    ),
                ),
                ("release_conditions", models.JSONField(blank=True, default=dict)),
                ("requires_transit_confirmation", models.BooleanField(default=False)),
                ("requires_purchase_proof", models.BooleanField(default=False)),
                ("requires_admin_validation", models.BooleanField(default=False)),
                ("requires_buyer_confirmation", models.BooleanField(default=False)),
                ("transit_confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "purchase_proof",
                    models.FileField(blank=True, null=True, upload_to="escrow-proofs/"),
                ),
                (
                    "purchase_proof_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "purchase_proof_uploaded_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("admin_validated_at", models.DateTimeField(blank=True, null=True)),
                ("buyer_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("frozen_reason", models.CharField(blank=True, max_length=240)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_validated_escrows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="beneficiary_escrows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "buyer_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="buyer_confirmed_escrows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escrows",
                        to="orders.order",
                    ),
                ),
                (
                    "purchase_proof_uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escrow_proof_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transit_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transit_confirmed_escrows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="LogisticsVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transit_agent_confirmed", models.BooleanField(default=False)),
                (
                    "transit_agent_confirmed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "purchase_proof",
                    models.FileField(
                        blank=True, null=True, upload_to="supplier-proof/"
                    ),
                ),
                (
                    "purchase_proof_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "purchase_proof_uploaded_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("admin_validated", models.BooleanField(default=False)),
                ("admin_validated_at", models.DateTimeField(blank=True, null=True)),
                ("fraud_flagged", models.BooleanField(default=False)),
                ("fraud_reason", models.CharField(blank=True, max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_admin_validations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logistics_verification",
                        to="orders.order",
                    ),
                ),
                (
                    "purchase_proof_uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_proof_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transit_agent_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_confirmations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier_escrow",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logistics_verification",
                        to="orders.orderescrow",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="orderescrow",
            constraint=models.UniqueConstraint(
                fields=("order", "escrow_type"), name="uniq_order_escrow_type"
            ),
        ),
    ]
