# Generated by Django 5.1.6 on 2026-03-03 23:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transportprofile',
            name='average_eta_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transportprofile',
            name='max_payload_kg',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transportprofile',
            name='operating_zones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transportprofile',
            name='vehicle_types',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddConstraint(
            model_name='transportquote',
            constraint=models.UniqueConstraint(fields=('shipment', 'transit_agent'), name='uniq_quote_per_agent_per_shipment'),
        ),
    ]
