# Generated by Django 5.1.6 on 2026-04-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0003_shipmentdispute_admin_decision_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="transport_mode",
            field=models.CharField(
                choices=[("AIR", "Avion"), ("SEA", "Bateau")],
                default="SEA",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="transportprofile",
            name="air_price_per_kg",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="transportprofile",
            name="sea_price_per_kg",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
