# Generated by Django 5.1.6 on 2026-06-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0009_shipment_delivery_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="current_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="current_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="location_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
