# Generated by Django 5.1.6 on 2026-07-16 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "logistics",
            "0010_shipment_current_latitude_shipment_current_longitude_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="pickup_otp_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="pickup_otp_hash",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name="DispatchOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Proposee"),
                            ("ACCEPTED", "Acceptee"),
                            ("REFUSED", "Refusee"),
                            ("EXPIRED", "Expiree"),
                            ("CANCELLED", "Annulee"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_offers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_offers",
                        to="logistics.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "expires_at"],
                        name="idx_dispatch_status_expires",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("shipment", "driver"),
                        name="uniq_dispatch_offer_per_driver",
                    )
                ],
            },
        ),
    ]
