# Generated by Django 5.1.6 on 2026-07-17 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("ORDERS", "Commandes"),
                    ("PAYMENTS", "Paiements"),
                    ("WALLET", "Wallet"),
                    ("DELIVERIES", "Livraisons"),
                    ("RENTALS", "Locations"),
                    ("KYC", "KYC"),
                    ("DISPUTES", "Litiges"),
                    ("PROMOTIONS", "Promotions"),
                    ("SECURITY", "Securite"),
                    ("ADMIN", "Administration"),
                    ("SYSTEM", "Systeme"),
                ],
                db_index=True,
                default="SYSTEM",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="priority",
            field=models.CharField(
                choices=[
                    ("LOW", "Faible"),
                    ("NORMAL", "Normale"),
                    ("HIGH", "Haute"),
                    ("CRITICAL", "Critique"),
                ],
                default="NORMAL",
                max_length=8,
            ),
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("promotions_enabled", models.BooleanField(default=True)),
                ("push_enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
