# Generated by Django 5.1.6

import decimal
import uuid
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(
                    choices=[
                        ('ORDER_PAYMENT', 'Paiement commande'),
                        ('LOGISTICS_FEE', 'Frais logistique'),
                        ('DISPUTE_FREEZE', 'Gel litige'),
                        ('PLATFORM_GUARANTEE', 'Garantie plateforme'),
                    ],
                    db_index=True,
                    max_length=24,
                )),
                ('state', models.CharField(
                    choices=[
                        ('PENDING', 'En attente de fonds'),
                        ('LOCKED', 'Fonds verrouillés'),
                        ('PARTIALLY_RELEASED', 'Partiellement libéré'),
                        ('READY_TO_RELEASE', 'Prêt à libérer'),
                        ('FROZEN', 'Gelé (litige)'),
                        ('RELEASED', 'Libéré au bénéficiaire'),
                        ('REFUNDED', "Remboursé à l'acheteur"),
                        ('CANCELLED', 'Annulé'),
                    ],
                    db_index=True,
                    default='PENDING',
                    max_length=24,
                )),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('amount', models.DecimalField(
                    decimal_places=2,
                    max_digits=14,
                    validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.01'))],
                )),
                ('released_amount', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=14)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=14)),
                ('entity_type', models.CharField(db_index=True, max_length=60)),
                ('entity_id', models.CharField(db_index=True, max_length=80)),
                ('required_conditions', models.JSONField(default=list)),
                ('met_conditions', models.JSONField(default=list)),
                ('auto_release_at', models.DateTimeField(blank=True, null=True)),
                ('frozen_reason', models.CharField(blank=True, max_length=300)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary', models.ForeignKey(
                    help_text='Who receives funds on release',
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='escrow_holds_as_beneficiary',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('frozen_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='frozen_escrow_holds',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('payer', models.ForeignKey(
                    help_text='Who funded this escrow',
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='escrow_holds_as_payer',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EscrowRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('commission', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=14)),
                ('release_reason', models.CharField(blank=True, max_length=300)),
                ('ledger_transaction_id', models.UUIDField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('escrow_hold', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='releases',
                    to='escrow.escrowhold',
                )),
                ('released_by', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='processed_escrow_releases',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('released_to', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='received_escrow_releases',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EscrowTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_state', models.CharField(max_length=24)),
                ('to_state', models.CharField(max_length=24)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('escrow_hold', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='transitions',
                    to='escrow.escrowhold',
                )),
                ('triggered_by', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='triggered_escrow_transitions',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='escrowhold',
            index=models.Index(fields=['entity_type', 'entity_id'], name='idx_escrow_entity'),
        ),
        migrations.AddIndex(
            model_name='escrowhold',
            index=models.Index(fields=['beneficiary', 'state'], name='idx_escrow_beneficiary_state'),
        ),
        migrations.AddIndex(
            model_name='escrowhold',
            index=models.Index(fields=['state', 'auto_release_at'], name='idx_escrow_auto_release'),
        ),
    ]
