# Generated by Django 5.1.6 on 2026-04-22 14:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_order_logistics_price_order_order_type_and_more"),
        ("wallets", "0004_alter_wallettransaction_provider_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("CREDIT", "Credit"), ("DEBIT", "Debit")], max_length=8
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Depot"),
                            ("WITHDRAWAL", "Retrait"),
                            ("REFUND", "Remboursement"),
                            ("ESCROW_TRANSFER", "Transfert vers escrow"),
                            ("ESCROW_RELEASE", "Liberation escrow"),
                            ("PAYOUT", "Payout"),
                            ("COMMISSION", "Commission"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("SUCCESS", "Succes"),
                            ("FAILED", "Echec"),
                            ("REVERSED", "Annule"),
                        ],
                        default="SUCCESS",
                        max_length=10,
                    ),
                ),
                (
                    "available_before",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "available_after",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "locked_before",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "locked_after",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "pending_before",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "pending_after",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("reference", models.CharField(blank=True, max_length=160)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="wallet",
            name="available_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="wallet",
            name="locked_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="wallet",
            name="pending_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="walletwebhookevent",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="walletwebhookevent",
            name="processing_error",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("SUCCESS", "Succes"),
                    ("FAILED", "Echec"),
                    ("REVERSED", "Annule"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.CheckConstraint(
                condition=models.Q(("available_balance__gte", 0)),
                name="wallet_available_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.CheckConstraint(
                condition=models.Q(("locked_balance__gte", 0)),
                name="wallet_locked_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.CheckConstraint(
                condition=models.Q(("pending_balance__gte", 0)),
                name="wallet_pending_gte_zero",
            ),
        ),
        migrations.AddField(
            model_name="walletledgerentry",
            name="counterparty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wallet_ledger_counterparty_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="walletledgerentry",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wallet_ledger_created_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="walletledgerentry",
            name="escrow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="orders.orderescrow",
            ),
        ),
        migrations.AddField(
            model_name="walletledgerentry",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="walletledgerentry",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_entries",
                to="wallets.wallet",
            ),
        ),
        migrations.AddConstraint(
            model_name="walletledgerentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("wallet", "idempotency_key"),
                name="uniq_wallet_ledger_idempotency_key",
            ),
        ),
    ]
