# Generated by Django 5.1.6 on 2026-04-22 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0005_walletledgerentry_wallet_available_balance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyReconciliationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="PAYDUNYA", max_length=40)),
                ("report_date", models.DateField(unique=True)),
                (
                    "provider_net_flow",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "wallets_available_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "wallets_locked_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "wallets_pending_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "escrow_locked_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "platform_commission_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("unresolved_payout_count", models.PositiveIntegerField(default=0)),
                (
                    "variance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OK", "Conforme"),
                            ("ALERT", "Alerte"),
                            ("FAILED", "Echec"),
                        ],
                        default="OK",
                        max_length=10,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-report_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PayoutRetryJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("RETRYING", "Retry en cours"),
                            ("SUCCESS", "Succes"),
                            ("FAILED", "Echec definitif"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("next_retry_at", models.DateTimeField()),
                ("last_error", models.CharField(blank=True, max_length=240)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_retry",
                        to="wallets.wallettransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["next_retry_at", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "next_retry_at"],
                        name="idx_payout_retry_status_due",
                    )
                ],
            },
        ),
    ]
