# Generated by Django 5.1.6 on 2026-05-30 06:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0012_wallet_balance_invariants"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="idempotencyrecord",
            options={},
        ),
        migrations.RenameIndex(
            model_name="wallettransaction",
            new_name="idx_wtx_wallet_status_created",
            old_name="idx_wallettx_wallet_status_created",
        ),
    ]
