# Generated by Django 5.1.6 on 2026-07-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0013_alter_idempotencyrecord_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="dormancy_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="walletledgerentry",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("DEPOSIT", "Depot"),
                    ("WITHDRAWAL", "Retrait"),
                    ("REFUND", "Remboursement"),
                    ("ESCROW_TRANSFER", "Transfert vers escrow"),
                    ("ESCROW_RELEASE", "Liberation escrow"),
                    ("PAYOUT", "Payout"),
                    ("COMMISSION", "Commission"),
                    ("PENALTY", "Penalite"),
                ],
                max_length=20,
            ),
        ),
    ]
