# Generated by Django 5.1.6 on 2026-03-05 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_transportprofile_average_eta_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentdispute',
            name='admin_decision',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='shipmentdispute',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentdispute',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipmentdispute',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='shipment-disputes/'),
        ),
        migrations.AddField(
            model_name='shipmentdispute',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
