# Generated by Django 5.1.6

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(
                    choices=[
                        ('PRODUCT_QUALITY', 'Qualité produit'),
                        ('DELIVERY', 'Livraison'),
                        ('FINANCIAL', 'Financier'),
                        ('FRAUD', 'Fraude'),
                        ('PLATFORM', 'Plateforme'),
                        ('KYC', 'KYC/Conformité'),
                        ('OTHER', 'Autre'),
                    ],
                    db_index=True,
                    max_length=20,
                )),
                ('dispute_type', models.CharField(db_index=True, max_length=40)),
                ('state', models.CharField(
                    choices=[
                        ('OPEN', 'Ouvert'),
                        ('UNDER_REVIEW', 'En révision'),
                        ('AWAITING_EVIDENCE', 'En attente de preuves'),
                        ('ESCALATED', 'Escaladé admin'),
                        ('ARBITRATION', 'Arbitrage en cours'),
                        ('RESOLVED_BUYER', 'Résolu en faveur acheteur'),
                        ('RESOLVED_SELLER', 'Résolu en faveur vendeur'),
                        ('RESOLVED_SPLIT', 'Résolu — partage'),
                        ('CLOSED_NO_ACTION', 'Fermé sans action'),
                        ('APPEALED', 'Appel en cours'),
                    ],
                    db_index=True,
                    default='OPEN',
                    max_length=24,
                )),
                ('entity_type', models.CharField(max_length=60)),
                ('entity_id', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('escrow_hold_id', models.UUIDField(blank=True, null=True)),
                ('escrow_frozen_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('sla_due_at', models.DateTimeField(blank=True, null=True)),
                ('sla_breached', models.BooleanField(default=False)),
                ('resolution_outcome', models.CharField(blank=True, max_length=30)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('appeal_deadline', models.DateTimeField(blank=True, null=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('guarantee_fund_used', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accused_party', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='accused_dispute_cases',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('assigned_mediator', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='mediated_dispute_cases',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('opened_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='opened_dispute_cases',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('resolved_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='resolved_dispute_cases',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(
                    choices=[
                        ('OPENED', 'Ouvert'),
                        ('STATE_CHANGED', 'État modifié'),
                        ('EVIDENCE_ADDED', 'Preuve ajoutée'),
                        ('MEDIATOR_ASSIGNED', 'Médiateur assigné'),
                        ('MESSAGE_ADDED', 'Message ajouté'),
                        ('ESCROW_FROZEN', 'Escrow gelé'),
                        ('ESCROW_RELEASED', 'Escrow libéré'),
                        ('DECISION_MADE', 'Décision rendue'),
                        ('APPEAL_FILED', 'Appel déposé'),
                        ('ESCALATED', 'Escaladé'),
                        ('SLA_BREACH', 'SLA dépassé'),
                    ],
                    max_length=30,
                )),
                ('from_state', models.CharField(blank=True, max_length=24)),
                ('to_state', models.CharField(blank=True, max_length=24)),
                ('description', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='dispute_events_as_actor',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('dispute', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='events',
                    to='disputes.disputecase',
                )),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(
                    choices=[
                        ('PHOTO', 'Photo'),
                        ('VIDEO', 'Vidéo'),
                        ('DOCUMENT', 'Document'),
                        ('SCREENSHOT', "Capture d'écran"),
                        ('INSPECTION_REPORT', "Rapport d'inspection"),
                        ('CHAT_EXPORT', 'Export conversation'),
                    ],
                    max_length=20,
                )),
                ('file_key', models.CharField(max_length=300)),
                ('file_hash', models.CharField(max_length=64)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='evidences',
                    to='disputes.disputecase',
                )),
                ('uploaded_by', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='uploaded_case_evidences',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(max_length=30)),
                ('buyer_refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('seller_release_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reasoning', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='made_dispute_decisions',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('dispute', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='decision',
                    to='disputes.disputecase',
                )),
            ],
        ),
        migrations.AddIndex(
            model_name='disputecase',
            index=models.Index(fields=['state', 'sla_due_at'], name='idx_dispute_state_sla'),
        ),
        migrations.AddIndex(
            model_name='disputecase',
            index=models.Index(fields=['opened_by', 'state'], name='idx_dispute_opener_state'),
        ),
        migrations.AddIndex(
            model_name='disputecase',
            index=models.Index(fields=['entity_type', 'entity_id'], name='idx_dispute_entity'),
        ),
    ]
