# Generated by Django 5.1.6 on 2026-06-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app", models.CharField(max_length=32)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("android", "Android"),
                            ("ios", "iOS"),
                            ("web", "Web"),
                        ],
                        default="android",
                        max_length=16,
                    ),
                ),
                ("latest_version", models.CharField(default="0.0.0", max_length=32)),
                (
                    "min_supported_version",
                    models.CharField(default="0.0.0", max_length=32),
                ),
                ("download_url", models.URLField(blank=True)),
                ("update_message", models.JSONField(blank=True, default=dict)),
                ("maintenance_message", models.JSONField(blank=True, default=dict)),
                ("maintenance", models.BooleanField(default=False)),
                ("kill_switch", models.BooleanField(default=False)),
                ("feature_flags", models.JSONField(blank=True, default=dict)),
                ("config_version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["app", "platform"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("app", "platform"), name="uniq_app_platform"
                    )
                ],
            },
        ),
    ]
