# Generated by Django 5.1.6 on 2026-02-26 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='join_grouping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_transit_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_transit_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
