# Generated by Django 5.1.6 on 2026-04-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_order_logistics_price_order_order_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderescrow",
            name="status",
            field=models.CharField(
                choices=[
                    ("LOCKED", "Bloque"),
                    ("READY", "Pret a etre libere"),
                    ("PAYOUT_PENDING", "Payout en attente"),
                    ("RELEASED", "Libere"),
                    ("FROZEN", "Gele"),
                    ("REFUNDED", "Rembourse"),
                ],
                default="LOCKED",
                max_length=20,
            ),
        ),
    ]
