# Generated by Django 5.1.6 on 2026-04-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_alter_orderescrow_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="escrow_status",
            field=models.CharField(
                choices=[
                    ("HELD", "Bloque chez NotchPay"),
                    ("SPLIT_LOCKED", "Split escrow bloque"),
                    ("PARTIALLY_RELEASED", "Partiellement libere"),
                    ("FROZEN", "Gele"),
                    ("REFUNDED", "Rembourse"),
                    ("RELEASED", "Debloque au vendeur"),
                ],
                default="HELD",
                max_length=20,
            ),
        ),
    ]
