# Generated by Django 5.1.6 on 2026-07-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderreview",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="reviews/"),
        ),
        migrations.AddField(
            model_name="orderreview",
            name="seller_reply",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="orderreview",
            name="seller_reply_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
