# Generated by Django 5.1.6 on 2026-07-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0010_alter_orderescrow_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="seller_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="seller_response_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
