// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzCpx92PnNHNgQBWmqIKgAM29JXI0G_ws',
    appId: '1:355585940733:web:6dd74d5666cab0acb5b294',
    messagingSenderId: '355585940733',
    projectId: 'marche-cm',
    authDomain: 'marche-cm.firebaseapp.com',
    storageBucket: 'marche-cm.firebasestorage.app',
    measurementId: 'G-9JLTN5Z60P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOFtUk82Mf-ku8tWjCl74vKGbalTAwids',
    appId: '1:355585940733:android:a0e6e19a1818ff1cb5b294',
    messagingSenderId: '355585940733',
    projectId: 'marche-cm',
    storageBucket: 'marche-cm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoEOv4KgXwSFkdU0dOmA5WGS2AHyJ0OWE',
    appId: '1:355585940733:ios:7d9b222d734a933cb5b294',
    messagingSenderId: '355585940733',
    projectId: 'marche-cm',
    storageBucket: 'marche-cm.firebasestorage.app',
    iosBundleId: 'com.marche.clients',
  );
}
