// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBawWwSPk9Q7d-3Euj-ToJ4dlry7F9_Qc',
    appId: '1:713755103175:web:80986b1fd1804d302b53e2',
    messagingSenderId: '713755103175',
    projectId: 'market-cm-d074b',
    authDomain: 'market-cm-d074b.firebaseapp.com',
    storageBucket: 'market-cm-d074b.firebasestorage.app',
    measurementId: 'G-70PCPK1NCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUuktBNK9jpUhV9x1JjeeylSPJEseVrZQ',
    appId: '1:713755103175:android:a65badb4b1ed52ce2b53e2',
    messagingSenderId: '713755103175',
    projectId: 'market-cm-d074b',
    storageBucket: 'market-cm-d074b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA03yu915AMPZO65tTADFjUfslNL_xeCM8',
    appId: '1:713755103175:ios:33e8ddb5549c2e6c2b53e2',
    messagingSenderId: '713755103175',
    projectId: 'market-cm-d074b',
    storageBucket: 'market-cm-d074b.firebasestorage.app',
    iosBundleId: 'com.marche.clients',
  );
}
