# Generated by Django 5.1.6 on 2026-03-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bundle_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_options',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
