# Generated by Django 5.1.6 on 2026-04-04 19:52

from django.db import migrations, models
import random
import string


def _next_code(existing: set[str]) -> str:
    alphabet = string.ascii_uppercase + string.digits
    for _ in range(100):
        candidate = f"PRD-{''.join(random.choice(alphabet) for _ in range(10))}"
        if candidate not in existing:
            existing.add(candidate)
            return candidate
    raise RuntimeError("Impossible de generer un code de reference produit unique.")


def populate_product_reference_codes(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    existing = set(
        code for code in Product.objects.exclude(reference_code__isnull=True).values_list("reference_code", flat=True)
    )
    for product in Product.objects.filter(reference_code__isnull=True).iterator():
        product.reference_code = _next_code(existing)
        product.save(update_fields=["reference_code"])


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_product_bundle_items_product_variant_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="reference_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=24, null=True, unique=True
            ),
        ),
        migrations.RunPython(populate_product_reference_codes, migrations.RunPython.noop),
    ]
