# Generated by Django 5.1.6 on 2026-04-05 11:20

import decimal

from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_product_reference_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="weight_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                validators=[MinValueValidator(decimal.Decimal("0.001"))],
            ),
        ),
    ]
