# Generated by Django 5.1.6 on 2026-06-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="video_poster",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/posters/"
            ),
        ),
    ]
