# Generated by Django 5.1.6 on 2026-07-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0012_videocomment_parent_videocommentlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Brouillon"),
                    ("PUBLISHED", "Publie"),
                    ("SUSPENDED", "Suspendu"),
                    ("REJECTED", "Refuse"),
                    ("ARCHIVED", "Archive"),
                ],
                default="PUBLISHED",
                max_length=12,
            ),
        ),
    ]
