# Generated by Django 5.1.6 on 2026-07-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0014_product_status_backfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="listing_type",
            field=models.CharField(
                choices=[
                    ("PHYSICAL", "Produit physique"),
                    ("SERVICE", "Service"),
                    ("DIGITAL", "Produit numerique"),
                    ("JOB", "Offre d'emploi"),
                ],
                default="PHYSICAL",
                max_length=10,
            ),
        ),
    ]
