# Generated by Django 5.1.6 on 2026-07-16 03:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=24, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("category", models.CharField(blank=True, max_length=120)),
                (
                    "price_period",
                    models.CharField(
                        choices=[
                            ("HOUR", "Heure"),
                            ("DAY", "Jour"),
                            ("WEEK", "Semaine"),
                            ("MONTH", "Mois"),
                        ],
                        default="DAY",
                        max_length=8,
                    ),
                ),
                (
                    "price_per_period",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="rentals/images/"
                    ),
                ),
                (
                    "ownership_proof",
                    models.FileField(
                        blank=True, null=True, upload_to="rentals/ownership/"
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=120)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("PUBLISHED", "Publie"),
                            ("SUSPENDED", "Suspendu"),
                            ("ARCHIVED", "Archive"),
                        ],
                        default="PUBLISHED",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RentalBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("period_count", models.PositiveIntegerField(default=1)),
                ("rental_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "deposit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Demandee"),
                            ("PAID", "Payee (sequestre)"),
                            ("ACCEPTED", "Acceptee"),
                            ("IN_PROGRESS", "En cours"),
                            ("RETURNED", "Restituee"),
                            ("COMPLETED", "Terminee"),
                            ("REFUSED", "Refusee"),
                            ("DISPUTED", "En litige"),
                            ("REFUNDED", "Remboursee"),
                            ("CANCELLED", "Annulee"),
                        ],
                        default="REQUESTED",
                        max_length=12,
                    ),
                ),
                ("handover_otp_hash", models.CharField(blank=True, max_length=128)),
                (
                    "handover_otp_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("handover_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("return_otp_hash", models.CharField(blank=True, max_length=128)),
                ("return_otp_expires_at", models.DateTimeField(blank=True, null=True)),
                ("return_confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rental_released_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "deposit_returned_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "deposit_forfeited_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_owner_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "renter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="rentals.rentallisting",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RentalStateEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=12)),
                ("to_status", models.CharField(max_length=12)),
                ("note", models.CharField(blank=True, max_length=240)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="rentals/condition/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rental_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="rentals.rentalbooking",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
