# Generated by Django 5.1.6 on 2026-05-30 06:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0002_cached_balance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ledgeraccount",
            name="uniq_ledger_account_user",
        ),
        migrations.RenameIndex(
            model_name="ledgeraccount",
            new_name="idx_lacct_subtype_owner",
            old_name="idx_ledger_account_subtype_owner",
        ),
        migrations.RenameIndex(
            model_name="ledgeraccount",
            new_name="idx_lacct_type_active",
            old_name="idx_ledger_account_type_active",
        ),
        migrations.AddConstraint(
            model_name="ledgeraccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("owner__isnull", False)),
                fields=("sub_type", "owner"),
                name="uniq_lacct_user",
            ),
        ),
    ]
