# Generated by Django 5.1.6 on 2026-03-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='provider',
            field=models.CharField(blank=True, choices=[('MOBILE_MONEY', 'Mobile Money'), ('ORANGE_MONEY', 'Orange Money'), ('VISA', 'Visa'), ('MASTERCARD', 'MasterCard')], max_length=20),
        ),
    ]
