# Generated by Django 5.1.6 on 2026-04-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0003_walletotpchallenge_walletwebhookevent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MOBILE_MONEY", "Mobile Money"),
                    ("ORANGE_MONEY", "Orange Money"),
                    ("VISA", "Visa"),
                    ("MASTERCARD", "MasterCard"),
                    ("PAYPAL", "PayPal"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="walletwebhookevent",
            name="provider",
            field=models.CharField(default="PAYDUNYA", max_length=40),
        ),
    ]
