# Generated by Django 5.1.6 on 2026-04-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0006_dailyreconciliationreport_payoutretryjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreconciliationreport",
            name="provider_reported_balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
    ]
