# Generated by Django 5.1.6 on 2026-04-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0007_dailyreconciliationreport_provider_reported_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreconciliationreport",
            name="provider",
            field=models.CharField(default="NOTCHPAY", max_length=40),
        ),
        migrations.AlterField(
            model_name="walletwebhookevent",
            name="provider",
            field=models.CharField(default="NOTCHPAY", max_length=40),
        ),
    ]
