# Generated by Django 5.1.6 on 2026-03-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auditlog_action_key_user_kyc_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancedocument',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='compliance/previews/'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='location_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='location_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location_provider',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='compliancedocument',
            constraint=models.UniqueConstraint(fields=('user', 'doc_type'), name='uniq_user_compliance_doc_type'),
        ),
    ]
