# Generated by Django 5.1.6 on 2026-04-04 19:52

from django.db import migrations, models
import random
import string


def _next_code(existing: set[str]) -> str:
    alphabet = string.ascii_uppercase + string.digits
    for _ in range(100):
        candidate = f"USR-{''.join(random.choice(alphabet) for _ in range(10))}"
        if candidate not in existing:
            existing.add(candidate)
            return candidate
    raise RuntimeError("Impossible de generer un code de reference utilisateur unique.")


def populate_user_reference_codes(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    existing = set(
        code for code in User.objects.exclude(reference_code__isnull=True).values_list("reference_code", flat=True)
    )
    for user in User.objects.filter(reference_code__isnull=True).iterator():
        user.reference_code = _next_code(existing)
        user.save(update_fields=["reference_code"])


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_encrypt_user_pii_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reference_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=24, null=True, unique=True
            ),
        ),
        migrations.RunPython(populate_user_reference_codes, migrations.RunPython.noop),
    ]
