# Generated by Django 5.1.6 on 2026-05-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_fcmtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancedocument",
            name="consent_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="compliancedocument",
            name="consent_version",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="compliancedocument",
            name="signature_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="compliance/signatures/"
            ),
        ),
    ]
