# Generated by Django 5.1.6 on 2026-06-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_passwordresetchallenge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("GENERAL_ADMIN", "Administrateur General"),
                    ("SUPPLIER", "Fournisseur"),
                    ("WHOLESALER", "Grossiste"),
                    ("TRANSIT_AGENT", "Livreur"),
                    ("BUYER", "Acheteur"),
                ],
                default="BUYER",
                max_length=20,
            ),
        ),
    ]
