# Generated by Django 5.1.6 on 2026-06-28 00:47

from django.db import migrations, models


def merge_wholesalers_into_suppliers(apps, schema_editor):
    """Fusion du compte Grossiste dans le compte Vendeur unifié (clé SUPPLIER)."""
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="WHOLESALER").update(role="SUPPLIER")


def noop_reverse(apps, schema_editor):
    # Irréversible métier (on ne sait pas distinguer les ex-grossistes) : no-op.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_alter_user_role"),
    ]

    operations = [
        migrations.RunPython(merge_wholesalers_into_suppliers, noop_reverse),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("GENERAL_ADMIN", "Administrateur General"),
                    ("SUPPLIER", "Vendeur"),
                    ("WHOLESALER", "Grossiste (déprécié)"),
                    ("TRANSIT_AGENT", "Livreur"),
                    ("BUYER", "Acheteur"),
                ],
                default="BUYER",
                max_length=20,
            ),
        ),
    ]
