# Generated by Django 5.1.6 on 2026-07-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin_scope",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUPER", "Super Administrateur"),
                    ("OPERATIONS", "Administrateur Operationnel"),
                    ("KYC", "Administrateur KYC"),
                    ("SUPPORT", "Administrateur Support"),
                ],
                default="",
                max_length=12,
            ),
        ),
    ]
