# Generated by Django 5.1.6 on 2026-04-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_user_reference_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wallet_pin_failed_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="wallet_pin_locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
