# Generated by Django 5.1.6 on 2026-07-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_messagereceipt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Texte"),
                    ("IMAGE", "Image"),
                    ("VIDEO", "Video"),
                    ("DOCUMENT", "Document"),
                    ("AUDIO", "Note vocale"),
                ],
                default="TEXT",
                max_length=10,
            ),
        ),
    ]
