apiVersion: v1
kind: Service
metadata:
  name: {{ include "marche-cm.fullname" . }}-web
  labels:
    {{- include "marche-cm.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    {{- include "marche-cm.selector" (merge (dict "component" "web") .) | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
