{{- if .Values.web.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "marche-cm.fullname" . }}-web
  labels:
    {{- include "marche-cm.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  minAvailable: {{ .Values.web.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "marche-cm.selector" (merge (dict "component" "web") .) | nindent 6 }}
{{- end }}
