name: clients_app
description: Application Clients (acheteurs) - Marche CM marketplace
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  web_socket_channel: ^3.0.1
  http: ^1.2.2
  video_player: ^2.9.2
  chewie: ^1.8.5
  cached_network_image: ^3.4.1
  file_picker: ^8.1.2
  google_sign_in: ^6.2.1
  shared_preferences: ^2.3.2
  country_picker: ^2.0.27
  url_launcher: ^6.2.6
  lucide_icons: ^0.257.0
  animations: ^2.0.11
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon_source.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/app_icon_source.png"
    background_color: "#FFFFFF"
    theme_color: "#15803D"
  windows:
    generate: true
    image_path: "assets/app_icon_source.png"
    icon_size: 256
  macos:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - assets/payment/mtn.png
    - assets/payment/orange.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
