# Generated by Django 5.1.6 on 2026-07-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycdocument",
            name="expiry_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="kycdocument",
            name="expiry_warning_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="kycapplication",
            name="target_level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Aucun"),
                    (1, "KYC Basique (ID)"),
                    (2, "KYC Avancé (Location / renforcé)"),
                    (3, "Compte Professionnel (RCCM/NIU)"),
                ]
            ),
        ),
    ]
